theme: jekyll-theme-cayman

url                      : "https://ParkHaeChan.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
