# Triggered when code is pushed to any branch in a repository
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: build
        run: chmod +x script/bootstrap
      - name: test
        run: script/cibuild